#!/usr/bin/env bash

set -e
set -o pipefail
trap 'printf -- "-- \033[0;36m${BASH_COMMAND}\033[0m\n"' DEBUG

# add local bin directory to PATH
export PATH="$(pwd)/bin:${PATH}"

# set up a git repository and run `git increment`
test_target=$(mktemp -d)
trap 'rm -rf "${test_target}"' EXIT
mkdir -p "${test_target}/local"
cd "${test_target}/local"
git init
echo "Hello" >README.md
git add README.md
git commit -m "Initial commit"

git tag v1.2.3

# increment by patch, minor, major
git increment patch
git increment minor
git increment major

# verify the tags
if [[ $(git tag --list | grep 'v1.2.4') == "" ]]; then
  echo "Expected tag v1.2.4 not found"
  exit 1
fi
if [[ $(git tag --list | grep 'v1.3.0') == "" ]]; then
  echo "Expected tag v1.3.0 not found"
  exit 1
fi
if [[ $(git tag --list | grep 'v2.0.0') == "" ]]; then
  echo "Expected tag v2.0.0 not found"
  exit 1
fi
